### ISSUE TITLE
表格数字错误

### ISSUE THREAD

**Issue by jelipo** [mohanson/accu#28]
表格中的opcode错误，与下面代码不一样<br><br>
发现的：**LD A, (HL+)、LD A, (HL-)**<br><br>
![image](https://user-images.githubusercontent.com/16136814/85375276-a5234600-b568-11ea-872e-f6ea5653c297.png)

**Comment by mohanson** [comment]
Fixed in https://github.com/mohanson/accu/pull/29

**Comment by jelipo** [comment]
@mohanson 相邻的 LD A, (HL+)、LD A, (HL-) 没有修改 😅

**Comment by mohanson** [comment]
再次感谢, 已经修改. https://github.com/mohanson/accu/commit/9bad3a9cf3a5830c6ae48548ed8e9f3059c9c7be
