### ISSUE TITLE
关于原创性的疑问

### ISSUE THREAD

**Issue by hsqStephenZhang** [mohanson/accu#36]
在油管上看到了这个视频 https://www.youtube.com/watch?v=_56TFhY9s1I
继续搜索相关内容后，发现了 https://accu.cc/content/misc/proof_of_god_existence/ ，也就是本仓库中的内容，进而发现，这两者几乎一模一样。
我很高兴，有同样对这个问题感兴趣的人，有对应的文章内容，从而可以浏览文字内容，但是，我不知道究竟哪一个是原创？如果此仓库的内容不是原创（考虑到是该视频先发布，我更倾向是这种情况，而不是该视频涉嫌洗稿，如果不是，我也真诚道歉），是否应该在文章中说明一下更为合理？

**Comment by mohanson** [comment]
你好, 在"杂项"章节中, 有两篇文章是我在读书会上分享的演讲稿 1. 中本聪为什么不给比特币设计最终一致性 2. 神的存在性证明. 这两篇分享稿内容全部来自他人的文章或视频. 我会在文章开头著名原作者.

**Comment by hsqStephenZhang** [comment]
that would by so nice of you

**Comment by mohanson** [comment]
已更新作者信息, 感谢您对作者权力的关心~

https://github.com/mohanson/accu/commit/8e5571aae6ac03fd525cdf8ba0e9ffcf411fffa6
